### ISSUE TITLE
`make install` issues

### ISSUE THREAD

**Issue by makew0rld** [solbu/igal2#2]
Thanks for creating this project.

When I first ran the Makefile, using GNU Make on Linux, I got this output and error:

```
install -d /usr/local/bin
install -m 0755 igal2 /usr/local/bin
ln -si igal2 /usr/local/bin/igal
install -m 0755 utilities/igal2.sh /usr/local/bin
install -d /usr/local/share/man/man1
install: cannot create directory ‘/usr/local/share/man/man1’: File exists
make: *** [Makefile:29: install] Error 1
```

Commenting out the `install -d /usr/local/share/man/man1` line lead to this output and error instead:

```
install -d /usr/local/bin
install -m 0755 igal2 /usr/local/bin
ln -si igal2 /usr/local/bin/igal
install -m 0755 utilities/igal2.sh /usr/local/bin
#install -d /usr/local/share/man/man1
install -m 0644 igal2.1 /usr/local/share/man/man1
install -d /usr/local/share/igal2
install -m 0644 README ChangeLog COPYING indextemplate2.html slidetemplate2.html tile.png igal2.css directoryline2.html /usr/local/share/igal2
sed -i 's_/usr/local_/usr/local_' /usr/local/bin/igal2 /usr/local/bin/igal2.sh /usr/local/share/man/man1/igal2.1
sed: can't read /usr/local/share/man/man1/igal2.1: Not a directory
make: *** [Makefile:33: install] Error 2
```

Since I'm using the same default prefix, I commented out the `sed` line as well. At that point I was able to successfully install it.

**Comment by solbu** [comment]
What distro and version are you running?
I can't recreate the error on my Mageia system.

**Comment by makew0rld** [comment]
Arch Linux, with GNU Make 4.3.

**Comment by solbu** [comment]
I just tried on a system I know has GNU Make 4.3, and I can't reproduce the error…

**Comment by makew0rld** [comment]
Ok, it works fine now. For some reason `/usr/local/share/man/man1` was a file that contained the igal2 manpage. Not sure how that happened, but once I deleted it I was able to use the original makefile. Thanks.
